version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=ABCBankDB;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
    
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Your_password123"
    ports:
    - "1433:1433"